INSERT INTO Song (SongId, Name, Explicit, Length, Likedness, AlbumId)
VALUES (UUID(), 'That Was Just Your Life ', FALSE, 300, 100, @DEATH),
       (UUID(), 'The End of the Line ', FALSE, 300, 100, @DEATH),
       (UUID(), 'Broken, Beat & Scarred ', FALSE, 300, 100, @DEATH),
       (UUID(), 'The Day That Never Comes ', FALSE, 300, 100, @DEATH),
       (UUID(), 'All Nightmare Long ', FALSE, 300, 100, @DEATH),
       (UUID(), 'Cyanide ', FALSE, 300, 100, @DEATH),
       (UUID(), 'The Unforgiven III ', FALSE, 300, 100, @DEATH),
       (UUID(), 'The Judas Kiss ', FALSE, 300, 100, @DEATH),
       (UUID(), 'Suicide & Redemption ', FALSE, 300, 100, @DEATH),
       (UUID(), 'My Apocalypse', FALSE, 300, 100, @DEATH),
       (UUID(), 'Atlas Rise!', FALSE, 300, 100, @HARDWIRED),
       (UUID(), 'Dyers Eve', FALSE, 300, 100, @AJFA),
       (UUID(), 'It Gets Funkier IV', FALSE, 300, 100, @HILL),
       (UUID(), 'Animal Spirits', FALSE, 300, 100, @GAME),
       (UUID(), 'Beastly', FALSE, 300, 100, @PECK),
       (UUID(), 'Smooth Move', FALSE, 300, 100, @SMOOTH);